# This is a GitHub actions workflow for NCEPLIBS-g2.
#
# This builds on the Intel compilers.
#
# Ed Hartnett, 12/22/22, Alex Richert
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  schedule:
    # Run monthly
    - cron: '0 0 1 * *'
  workflow_dispatch:

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: "oneapi"
            image: nceplibs-develop-ubuntu-24.04-oneapi-2025.3-intel-oneapi-mpi-2021.17
          - compiler: "classic"
            image: nceplibs-develop-ubuntu-24.04-classic-2023.2.1-intel-oneapi-mpi-2021.17
    name: "(${{ matrix.compiler }})"
    container:
      image: ghcr.io/noaa-emc/ci-common-build-cache/${{ matrix.image }}
      volumes:
        - /home/runner:/root

    steps:

    - name: "Install Intel"
      shell: bash
      run: |
        cd /opt/
        ./install-intel.sh
        set -a
        source /opt/intel/oneapi/setvars.sh
        set +a
        printenv | grep -E '^[a-zA-Z_][a-zA-Z0-9_]*=' >> $GITHUB_ENV

    - name: load-env
      shell: bash
      run: |
        set -a
        source /entrypoint.sh
        set +a
        printenv | grep -E '^[a-zA-Z_][a-zA-Z0-9_]*=' >> $GITHUB_ENV

    # - name: install-dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev libblas-dev liblapack-dev

    # - name: "Build dependencies"
    #   uses: NOAA-EMC/ci-build-nceplibs@develop
    #   with:
    #     bacio-version: develop
    #     jasper-version: version-4.0.0
    #     w3emc-version: develop
    #     w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF
    #     ip-version: develop
    #     g2c-version: develop
    #     key-prefix: Intel-

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2

    - name: build
      run: |
        if [ "${{ matrix.compiler }}" = "oneapi" ]; then
          export CC=icx
          export CXX=icpx
          export FC=ifx
        else
          export CC=icc
          export CXX=icpc
          export FC=ifort
        fi
        cd g2
        mkdir build
        cd build
        cmake .. -DBUILD_UTILS=OFF
        make -j2

    - name: test
      run: |
        cd g2/build
        ctest --verbose
