# This is a GitHub actions workflow for NCEPLIBS-g2.
#
# This builds the develop branch on MacOS.
#
# Ed Hartnett, 12/22/22
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc

    strategy:
      fail-fast: true
      matrix:
        jasper-version: [4.0.0]
        bacio-version: [2.4.1, 2.6.0]
        
    steps:
    - name: install-dependencies
      run: |
        find /Library/Frameworks/ -name "png*"
        sudo rm -rf /Library/Frameworks/Mono.framework
        #brew update
        brew install libpng
        brew install jpeg-turbo

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: v${{ matrix.bacio-version }}
        g2c-version: develop
        g2c-cmake-args: -DENABLE_SHARED=ON
        jasper-version: version-${{ matrix.jasper-version }}
        w3emc-version: v2.10.0
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF
        ip-version: develop

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2

    - name: build
      run: |
        cd g2
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2c;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip" -DCMAKE_BUILD_TYPE=Debug -DBUILD_UTILS=ON ..
        make -j2 VERBOSE=1

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2/build
        ctest  --output-on-failure
